#!/bin/bash

function get_record_type {
  local subdomain=$1
  local domain=$2

  dig $subdomain.$domain +short | awk 'NR==1{if (/^([0-9]{1,3}\.){3}[0-9]{1,3}$/) print "A"; else if (/^.*CNAME.*$/) print "CNAME"}'
}

function get_destination {
  local subdomain=$1
  local domain=$2

  dig $subdomain.$domain +short
}

domain=$1
subdomain=${2:-""}

if [[ $subdomain != "" ]]; then
  record_type=$(get_record_type $subdomain $domain)
  destination=$(get_destination $subdomain $domain)
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
else
  subdomains=("www" "lb-01" "web-01" "web-02")
  for subdomain in "${subdomains[@]}"
  do
    record_type=$(get_record_type $subdomain $domain)
    destination=$(get_destination $subdomain $domain)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  done
fi

