#!/usr/bin/env bash

# Update package lists and install HAproxy
apt-get update
apt-get -y install haproxy

# Backup the original HAproxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Write new HAproxy configuration file
cat > /etc/haproxy/haproxy.cfg << EOF
frontend http-in
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server web-01 90966-web-01-web-01:80 check
    server web-02 90966-web-02-web-02:80 check
EOF

# Restart HAproxy service
systemctl restart haproxy

# Make sure HAproxy is enabled on startup
systemctl enable haproxy

