#!/usr/bin/env bash
server {
    # Use IP of server as domain name
    server_name 54.162.46.10;

    # Customize HTTP response header
    add_header  X-Served-By 90966-web-01;

    # Serve /airbnb-onepage/ route from AirBnB_clone_v2
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }
}
